services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - app:/app
      - /app/backend/node_modules
    depends_on:
      database:
        condition: service_healthy
    command: [ sh, -c, "npx sequelize-cli db:migrate && npm run dev"]
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: "dev_user"
      POSTGRES_PASSWORD: "dev_password"
      POSTGRES_DB: "dev_movie_reservation_db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d dev_movie_reservation_db -U dev_user"]
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  app: